"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
scan_timeout = 10

[character]
error_symbol = "[â¯](bold red)"
format = "[\\$](green bold) "
success_symbol = "[â¯](bold green)"

[directory]
truncate_to_repo = false
truncation_length = 100
truncation_symbol = "â€¦/"

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[git_branch]
symbol = "ïˆ "

[username]
disabled = false
format = "[$userğŸŒ±]($style) "
show_always = true
style_root = "black bold"
style_user = "white bold"

[aws]
disabled = true

[gcloud]
disabled = true
