[[plugins]]
repo = 'Shougo/dein.vim'

# カーソル位置のコンテキストに合わせてftを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# カーソル位置のコンテキストのftを判定するライブラリ
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# 括弧などの入力補助
[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = "cohama/vim-smartinput-endwise"

# 括弧を虹色にする
[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

# visually indent guide
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# Align : 高機能整形・桁揃えプラグイン
[[plugins]]
repo = 'junegunn/vim-easy-align'

# EditorConfig : プロジェクト毎のエディタ設定読み込み
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# マルチバイト対応の整形
[[plugins]]
repo = 'h1mesuke/vim-alignta'

# surround.vim : テキストを括弧で囲む／削除する
[[plugins]]
repo = 'tpope/vim-surround'

# sudoedit
[[plugins]]
repo = 'vim-scripts/SudoEdit.vim'

#  行末の空白を強調表示
[[plugins]]
repo = 'bitc/vim-bad-whitespace'

# smooth_scroll.vim : スクロールを賢く
[[plugins]]
repo = 'vim-scripts/Smooth-Scroll'

# vim-smartword : 単語移動がスマートな感じで
[[plugins]]
repo = 'vim-scripts/smartword'

# anzu.vim : 現在の検索位置を画面に表示する
[[plugins]]
repo = 'osyo-manga/vim-anzu'

# ステータスラインをカッコよくする
[[plugins]]
repo = 'itchyny/lightline.vim'

# j/k移動を加速
[[plugins]]
repo = 'rhysd/accelerated-jk'

# vimからGitを操作
[[plugins]]
repo = 'tpope/vim-fugitive'

# Gitの追加/削除/変更された行を行番号の左に表示し
[[plugins]]
repo = 'airblade/vim-gitgutter'

# カラースキーマ
[[plugins]]
repo = 'tomasr/molokai'

# GitHub Copilot
[[plugins]]
repo = 'github/copilot.vim'
